name: Scala Steward

on:
  push:
  # manual trigger
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: npalm/action-app-token@v1.0.0
        with:
          appId: 103842
          appPrivateKeyBase64: ${{ secrets.AUTHOR_APP_PRIVATE_KEY }}
          appInstallationType: user
          appInstallationValue: laughedelic

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          # used to list repositories:
          github-app-id: 104507
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
          # used to author pull requests:
          github-token: ${{ steps.generate-token.outputs.token }}
          author-email: 80228653+laughedelic[bot]@users.noreply.github.com
          author-name: laughedelic[bot]
