name: Scala Steward

on:
  # manual trigger
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
      - name: Launch Scala Steward
        uses: laughedelic/scala-steward-action@gh-app-args
        with:
          # used to list repositories:
          github-app-id: 104507
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
          # used to author pull requests:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
